# Renovate Dependency Update Pipeline
# This pipeline runs Renovate to automatically create PRs for dependency updates.

trigger: none

schedules:
- cron: '0 8 * * 1'
  displayName: Weekly Renovate Run
  branches:
    include:
    - main
  always: true

parameters:
- name: dryRun
  displayName: Dry Run (preview without creating PRs)
  type: boolean
  default: false
- name: forceRecreatePR
  displayName: Force Recreate PR (recreate even if closed)
  type: boolean
  default: false

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

variables:
- name: gitHubRepo
  value: 'dotnet/arcade'

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows
    stages:
    - stage: Renovate
      displayName: Run Renovate
      jobs:
      - template: /eng/common/core-templates/job/renovate.yml@self
        parameters:
          dryRun: ${{ parameters.dryRun }}
          forceRecreatePR: ${{ parameters.forceRecreatePR }}
          gitHubRepo: ${{ variables.gitHubRepo }}
